### ISSUE TITLE
Administrator Features

### ISSUE THREAD

**Issue by realartin** [khodedawsh/marzneshin#128]
با عرض درود و خسته نباشید درخواست داشتم تا در صورت امکان این قابلیت ها رو به مرزنشین اضافه کنید :

 
- [ ] #135
- [ ] #136
- [ ] #138
- [ ] در بخش داشبورد درصد استفاده از منابع مانند هسته سی پی یو و هارد دیسک اضافه شود
- [ ] #137
 - [ ] لاگ هسته به صورت پیشفرض چند ثانیه اجرا می شود و سپس قطع می شود و سپس بعد ۱ دقیقه دوباره شروع میشود ، بعد نیست قابلیت استارت و استاپ دستی بهش اضافه بشود 
- [ ] فلو پیشفرض :
flow : xtls-rprx-viosion 
رو ادمین روت بتونه تعین کنه و هر ادمینی خواست reality استفاده کنه این فلو به صورت دیفالت بزایش تعین بشه و غیرقابل تغییر باشه براش مگر درصورت صلاح دید ادمین روت
- [ ]  #64 

اینها به نظرم جاشون خالیه و اگر اضافه شوند بسیار عالی می شود با تشکر 🙏❤️

**Comment by Krr0ptioN** [comment]
بهتر بود اینو تو قسمت discussion ایجاد میکردی.
