### ISSUE TITLE
[FEAT] show number of online(recently active) users

### ISSUE THREAD

**Issue by khodedawsh** [khodedawsh/marzneshin#138]
### UI Specification

- A barchart which shows the relative online user, offline user, not connected yet users.
- On the bottom of the chart, there should be a lengend or keys list to show the numbers of each group
- The feature will be displayed on users page and home page.

**Comment by Krr0ptioN** [comment]
This requires has to be detailed, on what page? which section?

**Comment by Krr0ptioN** [comment]
In #207 we manage to show online indicator for each user in the table
