### ISSUE TITLE
[BUG] Faild to update xray config in editor section of user settings sheet

### ISSUE THREAD

**Issue by Krr0ptioN** [khodedawsh/marzneshin#236]
**Describe the bug**
Admin aims to update the nodes xray config however faces an error event while client request api.

**To Reproduce**
1. Open a node
2. Switch to editor
3. Make some adjustment
4. Click apply

**Expected behavior**

**Screenshots**

![image](https://github.com/khodedawsh/marzneshin/assets/54506351/9c7b9a06-ba74-4410-940c-39fd9583c1a9)

**Comment by khodedawsh** [comment]
422 is returned when the request body isn't valid, in this case it's not valid json data.
I suppose the problem is the json not being validated in front-end hence it causes nothing but confusion for the user, even though it's essentially not a bug but rather lack of a feature.

**Comment by khodedawsh** [comment]
چرا زود تر ندیدمش. اگه دقت کنی آیدی نود اونجا undefined هست مشکل فرانته
