### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by mahdiismailpuri** [khodedawsh/marzneshin#237]
[BUG]
باگ موقع ادیت کردن هاست 
تغییرات ذخیره نمیشن و ارور میده 
ورژن : 0.2.0 
![Screenshot 2024-05-04 002236](https://github.com/khodedawsh/marzneshin/assets/135647913/a0f7099b-c74f-4544-b968-6cefa245e08e)

**Comment by Krr0ptioN** [comment]
#238 Duplicate
