### ISSUE TITLE
[BUG] While editing or creating host, 422 error is shown as reference to request failure to api

### ISSUE THREAD

**Issue by mahdiismailpuri** [khodedawsh/marzneshin#238]
[Bug]
موقع ساخت هاست با ارور مواجه میشم 
ورژن : 0.2.0 
![Screenshot 2024-05-04 002039](https://github.com/khodedawsh/marzneshin/assets/135647913/9f5b1c57-1f78-4713-901f-ddf00d575f67)

**Comment by khodedawsh** [comment]
![image](https://github.com/khodedawsh/marzneshin/assets/156741006/32f70218-5d7f-4b76-aa82-554b8fa3b7f0)

**Comment by Krr0ptioN** [comment]
This is will be resolved by #249
