### ISSUE TITLE
[BUG] The page is misdirected toward dashboard in instead of login page

### ISSUE THREAD

**Issue by mdjvd** [khodedawsh/Marzneshin#24]
بدون اینکه ادمین ساخته باشم مستقیم وارد داشبورد شد (البته بدون هیچ دسترسی ای، صرفا فقط وارد شد بدون ورود به صفحه لاگین)

![photo_2024-02-05_20-13-26](https://github.com/khodedawsh/Marzneshin/assets/116950557/a5c710e8-d8db-4acc-9a4a-6fd6b6e1edf0)

**Comment by Krr0ptioN** [comment]
#6
