### ISSUE TITLE
[bug] مشکل ارور api  هنگام ادیت حجم یوزر

### ISSUE THREAD

**Issue by mahdiismailpuri** [khodedawsh/marzneshin#248]
هنگام ادیت کردن حجم یوزر با ارور زیر مواجه میشوم 

![Screenshot 2024-05-10 162054](https://github.com/khodedawsh/marzneshin/assets/135647913/6a04abc7-900e-4e39-89f2-3413b6e2796a)

**Comment by khodedawsh** [comment]
fixed in https://github.com/khodedawsh/marzneshin/commit/a418d269839b3ff3e8b04877ea8572eaedd998ab.
