### ISSUE TITLE
[BUG] Core Settings Dialog - Xray Logs are not present in dialog

### ISSUE THREAD

**Issue by mdjvd** [khodedawsh/Marzneshin#25]
- لاگ ها نشون داده نمیشن (xray نصبه)

![image](https://github.com/khodedawsh/Marzneshin/assets/116950557/c7f9ff8b-034d-4cfe-9c9a-4aaf3715c5a2)

- کانفیگ xray رو نمیتونم تغییر بدم و این لاگ ها نشون داده میشن

![image](https://github.com/khodedawsh/Marzneshin/assets/116950557/79767b74-f5e7-4639-a46b-0b0247a02f6b)

**Comment by khodedawsh** [comment]
این یکی نیاز به کار فرانت اند هم داره @Krr0ptioN 
لاگ سالمه ولی کش تو بکند غیرفعاله بخاطر همین لاگ اولیه رو نشون نمیده
قسمت فرانت اند اینه که **قبلا کانکشن ظاهرا یجور اینتروال داشت و سرتایم رفرش میشد. الان asyncعه و در لحظه لاگ ها رو میفرسته.** بقیش بکنده

**Comment by Krr0ptioN** [comment]
> **قبلا کانکشن ظاهرا یجور اینتروال داشت و سرتایم رفرش میشد. **
چی رفرش میشد؟‌ رفتار درست الان چیه ؟ بارید عوض کنم به async ؟

**Comment by khodedawsh** [comment]
> > **قبلا کانکشن ظاهرا یجور اینتروال داشت و سرتایم رفرش میشد. **
> 
> چی رفرش میشد؟‌ رفتار درست الان چیه ؟ بارید عوض کنم به async ؟
> 
> @khodedawsh

سمت کلاینت رو نمیدونم. سمت سرور هر یک ثانیه دیتا رو میفرستاد. پارامتر اینتروال هم داشت که الان بلا استفاده شده. البته این متود هم کامل بعد ریفاکتور حذف میشه و برای هر نود مجزا استفاده میشه

**Comment by Krr0ptioN** [comment]
@khodedawsh 
این باگ ربطی به #48 داره؟
اگه مربوط به همون لاگ نود ها هست خب بهتره که بزاریمش کنار #12 چون همین الان در پروسه هست و اینم میشه اون بخش محیط UI که ایراد داره. هر چند تا وقتی که نهای نشه که لاگ ها قرار از چه پروتوکولی و با چه interface دریافت بشه این قسمت کار هم باقی میمونه.

**Comment by khodedawsh** [comment]
@Krr0ptioN 
آره دقیقا. قبلا فقط لاگ کور اصلی تو پنل مشخص بود. الان کور داخل مرزنشین حذف شده و در هر صورت باید لاگ نود ها مشخص باشه
و برای پروتکل هم مثل سابق websocket بهترین گزینست. یعنی توی فرانت همون دیالوگ core settings باید بیاد برای هر نود.
