### ISSUE TITLE
[BUG] Data limit field causes unpredictable behavior and change in entered value while editing user

### ISSUE THREAD

**Issue by mahdiismailpuri** [khodedawsh/marzneshin#252]
باگ ادیت حجم در نسخه "[fix host actions](https://github.com/khodedawsh/marzneshin/releases/tag/v0.3.0-alpha8) وجود دارد 
در چند بار ادیت اول اوکی بود اما وقتی عدد دورقمی ثبت میشد ارور میداد 
خودکار عدد های دو رقمی رو به عدد های بزرگ تبدیل میکنه 
![image](https://github.com/khodedawsh/marzneshin/assets/135647913/355a2e71-b378-4d2c-898e-a9910d99a219)

**Comment by Krr0ptioN** [comment]
Resolved by #258
