### ISSUE TITLE
Bug ساخت یوزر جدید 

### ISSUE THREAD

**Issue by mahdiismailpuri** [khodedawsh/marzneshin#253]
ساخت یوزر جدید با ارور مواجه میشود 
![image](https://github.com/khodedawsh/marzneshin/assets/135647913/534b195d-ab6c-46bf-97bb-c5efcecbd371)

نسخه : [fix host actions](https://github.com/khodedawsh/marzneshin/releases/tag/v0.3.0-alpha8)

**Comment by khodedawsh** [comment]
بخاطر یوزرنیم تکراریه. البته اینکه ارور رو درست نشون نمیده خودش بحثیه

**Comment by Krr0ptioN** [comment]
#255
