### ISSUE TITLE
[BUG] سیو نشدن تغییرات اعمال شده در کانفیگ xray 

### ISSUE THREAD

**Issue by mahdiismailpuri** [khodedawsh/marzneshin#254]
تغییرات در هسته xray سیو نمیشن 
پس از اعمال تغییرات پیغام is successfuly updated  دریافت میشود اما تغییرات سیو نشدن

**Comment by khodedawsh** [comment]
اینو من نتونستم بازتولید کنم. اگه تغییرات رو دقیق بزاری خوب میشه

**Comment by mahdiismailpuri** [comment]
اینباند جدید این مشکل رو دارم

**Comment by Krr0ptioN** [comment]
> اینباند جدید این مشکل رو دارم

من نتونستم ارور رو باز سازی بکنم. برای فهمیدن مشکل، بهتره که دیتایی اولیه، و دیتایی نهایی که حاصل تغییرات بوده رو نشون بدی. همینطور اگه میتونی لاگ های Developer Console هم تو قسمت network هم تو قسمت console نشون بدی.

@mahdiismailpuri

**Comment by khodedawsh** [comment]
بخاطر سینتکس اشتباه json بود @Krr0ptioN 
این که یه ولیدیشن تو فرانت بشه کافیه برای بستن ایشو

**Comment by Krr0ptioN** [comment]
ایدیتور خودش اعلام میکنه که یه اشتباهی در کد هست و خودکار validation انجام میده. 
اما یوزر میتونست دکمه ذخیره رو در هر صورت کلیک بکنه. #265 دکمه رو غیر فعال میکنه وقتی ورودی اشتباه. تا اینجا کار رو یکسره میکنه ولی هنوز جا برای بهتر کردنش هست. برای نمونه همون ارور ها رو به صورت پاپ نشون بده. که خارج از دامنه این ایشیو هست.
