### ISSUE TITLE
[BUG]: Relocate the menu items to their own page as page component

### ISSUE THREAD

**Issue by mdjvd** [khodedawsh/Marzneshin#26]
![image](https://github.com/khodedawsh/Marzneshin/assets/116950557/6a6a758e-14b8-41a9-b2e3-264057197571)

اگه کاربر توی صفحه home باشه هیچکدوم از اینا کار نمیکنن (هر کدوم برای کار کردن لازمه کاربر وارد اون صفحه مربوط توی سایدبار بشه)

مثلا توی صفحه هومبا زدن reset all usages اتفاقی نمیفته، و همین که کاربر وارد صفحه users بشه صفحه ای باز میشه برای ریست مصرف ها

یا host settings کار نمیکنه، و همین که وارد صفحه host سایدبار بشیم و بعدش هاست ها رو باز کنیم صفحه سیاه و not found میشه(صفحه هاست ستینگز غیرقابل دسترسی و استفاده است)

دکمه core settings هم فقط وقتی توی صفحه Nodes باشیم باز میشه

**Comment by khodedawsh** [comment]
دکمه ها بجز لاگوت و ریست یوزج باید حذف بشن

**Comment by Krr0ptioN** [comment]
- [ ] Host Settings 
- [ ] Nodes Settings, Nodes Usage
- [ ] Reset All Usages
