### ISSUE TITLE
[BUG] \کند بودن در جابه جایی در قسمت های مختلف پنل 

### ISSUE THREAD

**Issue by mahdiismailpuri** [khodedawsh/marzneshin#268]
جابه جایی در پنل با کندی همراه است برای مثال از قسمت هاست ها به یوزر ها 
و وقتی وارد قسمت یوزر ها میشی اول هیچ یوزری نشون نمیده و بعد از چند ثانیه یوزر ها ظاهر میشن 

همچنین حجم زیر یوزر ها غلط نمایش داده میشه 
برای مثال یوزر دارای 10 گیگ حجم زیرش 10.7 گیگ حجم نمایش میده 

![image](https://github.com/khodedawsh/marzneshin/assets/135647913/ade8f4d0-11b5-4ffe-aca1-4d363f9ce282)

**Comment by Krr0ptioN** [comment]
>همچنین حجم زیر یوزر ها غلط نمایش داده میشه
>برای مثال یوزر دارای 10 گیگ حجم زیرش 10.7 گیگ حجم نمایش میده

#271

**Comment by Krr0ptioN** [comment]
>جابه جایی در پنل با کندی همراه است برای مثال از قسمت هاست ها به یوزر ها
>و وقتی وارد قسمت یوزر ها میشی اول هیچ یوزری نشون نمیده و بعد از چند ثانیه یوزر ها ظاهر میشن

این مشکل در سرعت اینترنتته. ولی loader خواهیم گذاشت.

**Comment by Krr0ptioN** [comment]
#278
