### ISSUE TITLE
Bug مشکل در غیرفعال کردن یوزر 

### ISSUE THREAD

**Issue by mahdiismailpuri** [khodedawsh/marzneshin#269]
من حالت یوزر رو به غیر فعال تغییر دادم ولی پنل وضعیت اون ور همچنان اکتیو نشون میداد 
من کش مرورگر رو پاک کردم اما همچنان حالت یوزر اکتیو بود 
![image](https://github.com/khodedawsh/marzneshin/assets/135647913/19dc17fe-5a52-4054-a435-bb84ddf76720)

**Comment by Krr0ptioN** [comment]
وقتی یوزر غیر فعال شده مینویسه Enable. کلمه فعله. الان کلیک کنی دوباره فعال میشه.
