### ISSUE TITLE
[BUG] unable to revoke sub or reset usage and etc

### ISSUE THREAD

**Issue by mdjvd** [khodedawsh/Marzneshin#28]
- لینک ساب یوزر ریووک نمیشه و حجمش هم ریست نمیشه. اما حجم و نوت و تاریخ یوزر قابل ادیته

- and deleting a user takes a solid 20 seconds!

![image](https://github.com/khodedawsh/Marzneshin/assets/116950557/95e4bdb9-7b7d-447f-a926-911238fb5fdc)

**Comment by khodedawsh** [comment]
نه آین مال بکنده
