### ISSUE TITLE
[INVALID]: React form hook debugging plugin in production code

### ISSUE THREAD

**Issue by mdjvd** [khodedawsh/Marzneshin#29]
- با وارد شدن به صفحه سرویس ها،  این صفحه کناری میپره وسط و سریع میره کنار
- سرویس ها قابل تغییر وضعیت نیستن و حذف نمیشن

![image](https://github.com/khodedawsh/Marzneshin/assets/116950557/7867bcbf-a8bd-4626-9be1-027df003f1cf)

**Comment by Krr0ptioN** [comment]
اون ساید بار برای دیباگ کردن فروم هست و اضافی هست، باید پاک بشه. تغییر و حذف سرویس هم در #22 برنامه ریزی شده.
