### ISSUE TITLE
[BUG]: Not found JSON return when the page is refreshed on pages other than Home page

### ISSUE THREAD

**Issue by mdjvd** [khodedawsh/Marzneshin#30]
توی سایدبار اگه تو هر صفحه ای به جز home باشی و صفحه رو refresh کنی، یه صفحه مشکی با متن 
{"detail":"Not Found"}
نمایش داده میشه

![image](https://github.com/khodedawsh/Marzneshin/assets/116950557/96bef99c-e953-417d-b668-82f2b1381dff)
![image](https://github.com/khodedawsh/Marzneshin/assets/116950557/1f4ba70e-02f8-4a9e-9f27-ddf4609ed157)

**Comment by Krr0ptioN** [comment]
برای من قابل باز سازی نبود مراحلی که توضیح دادی. لاگ داخل Dev console و بکند چی میگه؟

**Comment by Krr0ptioN** [comment]
@khodedawsh مشکل در روتینگ سرویس ها در لود بالانسر یونیکورن هست. 

راهحل اینکه همه یه روت های که بعد داشبورد هستن به فرانت ریدایرکت بشه.

localhost:8000/dashboard/* --> localhost:6000/dashboard/*

**Comment by Krr0ptioN** [comment]
برنامه ریزی کردم برای سپرینت بعدی 

S3: QA & Maintanance

**Comment by khodedawsh** [comment]
fixed by https://github.com/khodedawsh/Marzneshin/pull/38
