### ISSUE TITLE
[BUG] xray config is sometimes empty and only shows []

### ISSUE THREAD

**Issue by khodedawsh** [khodedawsh/marzneshin#328]
when loading xray config for the first time (often on a remote server) the config is empty and only contains []

**Comment by Krr0ptioN** [comment]
Is it temporary or stay the same when you refresh the page? Does closing the settings window and reopening it again, resolves glitch?

**Comment by khodedawsh** [comment]
it gets fixed after reopening the sheet. no need to even refresh the page.

**Comment by Krr0ptioN** [comment]
I'll delegate this to 7 iteration.

**Comment by Krr0ptioN** [comment]
I was unable to reproduce this issue.
