### ISSUE TITLE
[BUG] Limited user isn't reenabled after increasing traffic limit

### ISSUE THREAD

**Issue by khodedawsh** [khodedawsh/marzneshin#372]
**Machine details (please complete the following information):**
 - OS: [e.g. ubuntu 20]
- Python version: [e.g 3.8]
- Nodejs version: [e.g 16.17]

**Additional context**

**Comment by Krr0ptioN** [comment]
@khodedawsh Is this related to #399 ?

**Comment by khodedawsh** [comment]
yep #399 would fix this
