### ISSUE TITLE
[IMPROVE] Spliting info section into subscription tab and info tab to promote higher cohesion and memorable user flow

### ISSUE THREAD

**Issue by Krr0ptioN** [khodedawsh/marzneshin#388]
## Description
User settings is very disorganized and confusing.

### User Interface Specification

![image](https://github.com/khodedawsh/marzneshin/assets/54506351/550e9786-64bc-4633-8ee8-276aa7eb8fa2)

**Comment by sakii-11** [comment]
hey @Krr0ptioN , can you assign this task to me?

**Comment by Krr0ptioN** [comment]
> hey @Krr0ptioN , can you assign this task to me?

Yes, good luck
