### ISSUE TITLE
[BUG] When a user is online, the total displayed user in pie chart is incorrect since it sums up active and online users together (v0.3.0)

### ISSUE THREAD

**Issue by melikalajevardi** [khodedawsh/marzneshin#389]
Hello, and thank you very much for your contribution to circumventing censorship in Iran.

In this version, the Home section includes a cumulative count of both online and active users. For example, if there is one active user who is also online, the total number of users will be displayed as 2.

**Comment by Krr0ptioN** [comment]
Thanks for consideration, this will be resolved by #390
