### ISSUE TITLE
api token time

### ISSUE THREAD

**Issue by thezass** [khodedawsh/marzneshin#393]
سلام
امکانش هست که توکن api ادمین بدون زمان ریست شدن باشه و یا زمانش خیلی طولانی باشه?

**Comment by Krr0ptioN** [comment]
داخل فایل .env متغییر ‍JWT_ACCESS_TOKEN_EXPIRE_MINUTES‍ رو برابر صفر قرار بده تا هیچ وقت توکن اکسپایر نشه. برای طولانی تر کردنش هم مقدارشو بیشتر کن.
