### ISSUE TITLE
[BUG] service dialog overflows in case there are too many inbounds

### ISSUE THREAD

**Issue by yremac** [khodedawsh/marzneshin#406]
### Current Behavior

With multiple inbounds in 1 node, there is no scroll bar and I cannot interact in any way.

### Steps To Reproduce

1. I create several incoming nodes on 1 node
2. I'm trying to create a service

### Screenshots

![img](https://github.com/khodedawsh/marzneshin/assets/113031864/c4e3b30a-2318-41e4-a503-7591f03dedf6)

### Environment

OS:

Browsers:chrome, firefox

Version: 0.3.0

**Comment by khodedawsh** [comment]
~15 inbounds is probably enough for a while but we'll consider this.
Why do you need this many inbounds though?

**Comment by Krr0ptioN** [comment]
This issue is resolved
