### ISSUE TITLE
[FEAT] make Xray logs available for each node

### ISSUE THREAD

**Issue by khodedawsh** [khodedawsh/Marzneshin#48]
## Description
Xray logs should be accessible through the api for each node

### Technical Interface Specification
- Marzneshin gets logs from marznode using a grpc stream and passes it to api clients using websocket

### Tasks

- [ ] make logs stream available on marznode
- [ ] create logs websocket api for marzneshin nodes

**Comment by Krr0ptioN** [comment]
#45 Depends on this as front-end completion.
