### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Imnonamee** [khodedawsh/marzneshin#483]
### Current Behavior

قسمت هاست اینباد  باگ داره نمیشه اسکرول کرد یکی دوتا اینباند اون پایینه هرچی میکشم صفحرو بالا نمیان روی گوشی اینطوری رو سیستم اطلاعی ندارم 

### Steps To Reproduce

1.hosts
2. Inbounds

### Screenshots

![IMG_20240807_153500_165](https://github.com/user-attachments/assets/7ea7c47e-8c84-40da-8168-daa338fa4b21)

### Environment

OS: 

Browsers: opera

Version: 83.3

**Comment by Krr0ptioN** [comment]
#480 تکراری.
