### ISSUE TITLE
[BUG] API used_traffic field does not work

### ISSUE THREAD

**Issue by m0x61h0x64i** [khodedawsh/marzneshin#489]
### Current Behavior

If u send a POST request to /api/users to create a user with used_traffic field, it just do not set the used_traffic amount

### Environment

Version: nightly

**Comment by khodedawsh** [comment]
I'm not surprised, used_traffic is an attribute of UserResponse and you can't modify used_traffic of a user using the api.

**Comment by m0x61h0x64i** [comment]
Thanks,
![image](https://github.com/user-attachments/assets/a9fdc2de-281c-4ba5-91aa-d9a43486fd8d)
It was available in the request example, so refactor if possible to avoid repeating same mistake in the future
