### ISSUE TITLE
[FEAT] storing node stats

### ISSUE THREAD

**Issue by khodedawsh** [khodedawsh/marzneshin#93]
## Description

Get and store node stats

### Tasks

- [ ] modify the protocol to send the node stats and implement in marznode
- [ ] get and record node stats

**Comment by Krr0ptioN** [comment]
Is there ready for the third Iteration?

**Comment by Krr0ptioN** [comment]
@khodedawsh What is the status of this issue?

**Comment by Krr0ptioN** [comment]
Is it related to #239 and #214
